name: 'publish'

on:
  push:
    branches: ["master"]

jobs:
  publish-tauri:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        platform: [ubuntu-20.04, windows-latest]

    runs-on: ${{ matrix.platform }}
    steps:

      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GIT_KEY }}
          submodules: true

      - name: Setup bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Build libakrypt
        uses: threeal/cmake-action@v1.3.0
        with:
          source-dir: libakrypt
          build-dir: libakrypt/build

      - name: Install Rust stable
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: nightly

      - name: Install dependencies (ubuntu only)
        if: matrix.platform == 'ubuntu-20.04'
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.0-dev libappindicator3-dev librsvg2-dev patchelf

      - name: install frontend dependencies
        run: bun install # change this to npm or pnpm depending on which one you use

      - uses: tauri-apps/tauri-action@v0
